---
apiVersion: v2
description: Chart for benphelps homepage
name: homepage
version: 0.0.2
appVersion: v0.14.18
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 0.2.2
annotations:
  artifacthub.io/changes: |-
    - kind: added
      description: RBAC is optional and an existing config map can be supplied for configuration.
