image:
  repository: ghcr.io/benphelps/homepage
  # tag: v0.4.18

# Enable RBAC. RBAC is necessary to use Kubernetes integration
enableRbac: false

serviceAccount:
  # Specify a different service account name
  name: homepage

service:
  main:
    ports:
      http:
        port: 3000

# Enable the ingress to expose Homepage to the network.
ingress:
  main:
    enabled: false
    # labels:
    #   # This label will enable discover of this deployment in Homepage
    #   homepage/enabled: "true"
    # annotations:
    #   # These annotations will configure how this deployment is shown in Homepage
    #   homepage/name: "Homepage"
    #   homepage/description: "A modern, secure, highly customizable application dashboard."
    #   homepage/group: "A New Group"
    #   homepage/icon: "homepage.png"
    # ingressClassName: "nginx"
    # hosts:
    #   - host: &host "homepage.example.com"
    #     paths:
    #       - path: /
    #         pathType: Prefix
    # tls:
    #   - hosts:
    #       - *host

# All the config files for Homepage can be specified under their relevant config block.
config:
  # To use an existing ConfigMap uncomment this line and specify the name
  # useExistingConfigMap: existing-homepage-configmap
  bookmarks:
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
  services:
    - My First Group:
        - My First Service:
            href: http://localhost/
            description: Homepage is awesome

    - My Second Group:
        - My Second Service:
            href: http://localhost/
            description: Homepage is the best

    - My Third Group:
        - My Third Service:
            href: http://localhost/
            description: Homepage is 😎
  widgets:
    - resources:
        # change backend to 'kubernetes' to use Kubernetes integration. Requires RBAC.
        backend: resources
        expanded: true
        cpu: true
        memory: true
    - search:
        provider: duckduckgo
        target: _blank
  kubernetes:
    # change mode to 'cluster' to use RBAC service account
    mode: disable
  docker:
  settings:

persistence:
  logs:
    enabled: true
    type: emptyDir
    mountPath: /app/config/logs

resources:
  requests:
    memory: 10Mi
    cpu: 10m
  limits:
    memory: 200Mi
    cpu: 500m
